services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urlshortener
    ports:
      - 5431:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
